### PR TITLE
Add the possibility to include helm charts in the generated csar file

### PR DESCRIPTION
**Pull request by thomas-melville**
Hi,

I didn't see any contributing guidelines so I hope this pull request is ok.
My company needs a csar file generator in our CI flow, we use helm charts so I'm updating the cli to be able to take in helm charts and store them in the correct location.

### CODE REVIEW

**Comment by thomas-melville** [comment]
Hi @lianhao 

I see you made the majority of the most recent commits.
Could you take a look at this pull request, or point me to the correct person?

**Comment by thomas-melville** [comment]
@kfrukacz-gs @chendave @jwagantall @Gaoweitao 

Hi all,
Could you take a look at this pull request, or point me in the right direction?

**Comment by lianhao** [comment]
@thomas-melville , Please follow https://wiki.onap.org/display/DW/Developing+ONAP to submit patches. Also I would suggest you use downstream code to add your support of helm. Because the helm definition file is not in the SOL-004 standard

**Comment by thomas-melville** [comment]
Thanks @lianhao

**Pull request closed without merging**
